# Generated by Django 3.1.13 on 2021-11-26 05:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cal', '0006_auto_20211126_0227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.AddField(
            model_name='event',
            name='day',
            field=models.DateField(default=datetime.datetime.now, help_text='Day of the event', verbose_name='Day of the event'),
        ),
        migrations.AddField(
            model_name='event',
            name='materials',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='event',
            name='meetid',
            field=models.TextField(default='1', help_text='meeting id', verbose_name='Meeting ID'),
        ),
        migrations.AddField(
            model_name='event',
            name='participant',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(help_text='Final time', verbose_name='Final time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(help_text='Starting time', verbose_name='Starting time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.TextField(help_text='name of the Meeting', verbose_name='Name of the Meeting'),
        ),
    ]
