# Generated by Django 3.1.13 on 2021-11-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0008_remove_event_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(help_text='Final time', verbose_name='Final time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(help_text='Starting time', verbose_name='Starting time'),
        ),
    ]
