# Generated by Django 3.2.8 on 2021-10-31 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_event_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='day',
            field=models.DateField(default=datetime.datetime.now, help_text='Day of the event', verbose_name='Day of the event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, help_text='Textual Notes', null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(help_text='Final time', verbose_name='Final time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(help_text='Starting time', verbose_name='Starting time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.TextField(help_text='name of the event', verbose_name='Name of the Event'),
        ),
    ]
