# Generated by Django 3.1.13 on 2021-11-28 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20211125_2107'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meeting',
        ),
    ]
